class Error:
    def handling_error(self):
        pass
